export const layouts = {
  // Service Insishgt
  ['service-insight']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'a4', x: 4, y: 0, w: 1, h: 1, static: true },
        { i: 'b2', x: 0, y: 1, w: 1.66, h: 2.5, static: true },
        { i: 'b3', x: 1.66, y: 1, w: 1.66, h: 2.5, static: true },
        { i: 'b4', x: 3.33, y: 1, w: 1.66, h: 2.5, static: true },
        { i: 'b1', x: 2.5, y: 3.5, w: 2.5, h: 2.5, static: true },
        { i: 'b0', x: 0, y: 3.5, w: 2.5, h: 2.5, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 1250,
      cols: 4,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1.33, h: 1, static: true },
        { i: 'a1', x: 1.33, y: 0, w: 1.33, h: 1, static: true },
        { i: 'a2', x: 2.66, y: 0, w: 1.33, h: 1, static: true },
        { i: 'a3', x: 0, y: 1, w: 2, h: 1, static: true },
        { i: 'a4', x: 2, y: 1, w: 2, h: 1, static: true },
        { i: 'b2', x: 0, y: 2, w: 2, h: 2.5, static: true },
        { i: 'b3', x: 2, y: 2, w: 2, h: 2.5, static: true },
        { i: 'b4', x: 0, y: 4.5, w: 2, h: 2.5, static: true },
        { i: 'b1', x: 2, y: 4.5, w: 2, h: 2.5, static: true },
        { i: 'b0', x: 0, y: 7, w: 4, h: 2.5, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 2, h: 1, static: true },
        { i: 'a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a2', x: 1, y: 1, w: 1, h: 1, static: true },
        { i: 'a3', x: 0, y: 2, w: 1, h: 1, static: true },
        { i: 'a4', x: 1, y: 2, w: 1, h: 1, static: true },
        { i: 'b2', x: 0, y: 3, w: 2, h: 2.5, static: true },
        { i: 'b3', x: 0, y: 5.5, w: 2, h: 2.5, static: true },
        { i: 'b4', x: 0, y: 8, w: 2, h: 2.5, static: true },
        { i: 'b0', x: 0, y: 10.5, w: 2, h: 2.5, static: true },
        { i: 'b1', x: 0, y: 13, w: 2, h: 2.5, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 2, h: 1, static: true },
        { i: 'a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 2, w: 1, h: 1, static: true },
        { i: 'a3', x: 0, y: 3, w: 1, h: 1, static: true },
        { i: 'a4', x: 0, y: 4, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 5, w: 2, h: 2.5, static: true },
        { i: 'b1', x: 0, y: 7.5, w: 2, h: 2.5, static: true },
        { i: 'b2', x: 0, y: 10, w: 2, h: 2.5, static: true },
        { i: 'b3', x: 0, y: 12.5, w: 2, h: 2.5, static: true },
        { i: 'b4', x: 0, y: 15, w: 2, h: 2.5, static: true },
        { i: 'b5', x: 0, y: 17.5, w: 2, h: 2.5, static: true },
        { i: 'b6', x: 0, y: 20, w: 2, h: 2.5, static: true },
        { i: 'b7', x: 0, y: 22.5, w: 2, h: 2.5, static: true },
      ],
    },
  ],
  ['user-engagement']: [
    {
      minSize: 980,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 1, w: 4, h: 5, static: true },
        { i: 'divider0', x: 0, y: 6, w: 4, h: 0.5, static: true },
        { i: 'c0', x: 0, y: 6.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 9.5, w: 4, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 10, w: 2, h: 3, static: true },
        { i: 'd1', x: 2, y: 10, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 13, w: 4, h: 0.5, static: true },
        { i: 'e0', x: 0, y: 13.5, w: 1, h: 1, static: true },
        { i: 'e1', x: 1, y: 13.5, w: 1, h: 1, static: true },
        { i: 'divider3', x: 0, y: 14.5, w: 4, h: 0.5, static: true },
        { i: 'f0', x: 0, y: 15, w: 1, h: 1, static: true },
        { i: 'f1', x: 0, y: 16, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a1', x: 1.5, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a2', x: 0, y: 1, w: 1.5, h: 1, static: true },
        { i: 'a3', x: 1.5, y: 1, w: 1.5, h: 1, static: true },
        { i: 'b0', x: 0, y: 2, w: 3, h: 5, static: true },
        { i: 'divider0', x: 0, y: 7, w: 4, h: 0.5, static: true },
        { i: 'c0', x: 0, y: 7.5, w: 3, h: 3, static: true },
        { i: 'divider1', x: 0, y: 10.5, w: 4, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 11, w: 3, h: 3, static: true },
        { i: 'd1', x: 0, y: 14, w: 3, h: 3, static: true },
        { i: 'divider2', x: 0, y: 17, w: 3, h: 0.5, static: true },
        { i: 'e0', x: 0, y: 17.5, w: 1.5, h: 1, static: true },
        { i: 'e1', x: 1.5, y: 17.5, w: 1.5, h: 1, static: true },
        { i: 'divider3', x: 0, y: 18.5, w: 3, h: 0.5, static: true },
        { i: 'f0', x: 0, y: 19, w: 1, h: 1, static: true },
        { i: 'f1', x: 0, y: 20, w: 3, h: 3, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a3', x: 1, y: 1, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 2, w: 3, h: 5, static: true },
        { i: 'divider0', x: 0, y: 7, w: 4, h: 0.5, static: true },
        { i: 'c0', x: 0, y: 7.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 10.5, w: 4, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 11, w: 2, h: 3, static: true },
        { i: 'd1', x: 0, y: 14, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 17, w: 2, h: 0.5, static: true },
        { i: 'e0', x: 0, y: 17.5, w: 1, h: 1, static: true },
        { i: 'e1', x: 1, y: 17.5, w: 1, h: 1, static: true },
        { i: 'divider3', x: 0, y: 18.5, w: 2, h: 0.5, static: true },
        { i: 'f0', x: 0, y: 19, w: 1, h: 1, static: true },
        { i: 'f1', x: 0, y: 20, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 2, w: 1, h: 1, static: true },
        { i: 'a3', x: 0, y: 3, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 4, w: 3, h: 5, static: true },
        { i: 'divider0', x: 0, y: 9, w: 4, h: 0.5, static: true },
        { i: 'c0', x: 0, y: 9.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 12.5, w: 4, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 13, w: 1, h: 3, static: true },
        { i: 'd1', x: 0, y: 16, w: 1, h: 3, static: true },
        { i: 'divider2', x: 0, y: 19, w: 1, h: 0.5, static: true },
        { i: 'e0', x: 0, y: 19.5, w: 2, h: 1, static: true },
        { i: 'e1', x: 0, y: 20.5, w: 2, h: 1, static: true },
        { i: 'divider3', x: 0, y: 21.5, w: 2, h: 0.5, static: true },
        { i: 'f0', x: 0, y: 22, w: 1, h: 1, static: true },
        { i: 'f1', x: 0, y: 23, w: 1, h: 3, static: true },
      ],
    },
  ],
  ['data-downloaded']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a1', x: 1.5, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a2', x: 0, y: 1, w: 2.5, h: 3, static: true },
        { i: 'a3', x: 2.5, y: 1, w: 2.5, h: 3, static: true },
        { i: 'a4', x: 0, y: 4, w: 2.5, h: 3, static: true },
        { i: 'a5', x: 2.5, y: 4, w: 2.5, h: 3, static: true },
        { i: 'map', x: 0, y: 7, w: 5, h: 6, static: true },
      ],
    },
    {
      minSize: 980,
      maxSize: 1250,
      cols: 4,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a1', x: 1.5, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a2', x: 0, y: 1, w: 2, h: 3, static: true },
        { i: 'a3', x: 2, y: 1, w: 2, h: 3, static: true },
        { i: 'a4', x: 0, y: 4, w: 2, h: 3, static: true },
        { i: 'a5', x: 2, y: 4, w: 2, h: 3, static: true },
        { i: 'map', x: 0, y: 7, w: 4, h: 6, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a1', x: 1.5, y: 0, w: 1.5, h: 1, static: true },
        { i: 'a2', x: 0, y: 1, w: 3, h: 3, static: true },
        { i: 'a3', x: 0, y: 4, w: 3, h: 3, static: true },
        { i: 'a4', x: 0, y: 7, w: 3, h: 3, static: true },
        { i: 'a5', x: 0, y: 10, w: 3, h: 3, static: true },
        { i: 'map', x: 0, y: 13, w: 3, h: 6, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 2, w: 3, h: 3, static: true },
        { i: 'a3', x: 0, y: 5, w: 3, h: 3, static: true },
        { i: 'a4', x: 0, y: 8, w: 3, h: 3, static: true },
        { i: 'a5', x: 0, y: 11, w: 3, h: 3, static: true },
        { i: 'map', x: 0, y: 14, w: 3, h: 6, static: true },
      ],
    },
  ],
  ['streamlined-data']: [
    {
      minSize: 790,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 5, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 2.5, h: 3, static: true },
        { i: 'a1', x: 2.5, y: 0.5, w: 2.5, h: 3, static: true },
        { i: 'divider1', x: 0, y: 4, w: 5, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 4.5, w: 1, h: 1, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 2, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 2, h: 3, static: true },
        { i: 'a1', x: 2.5, y: 3.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 7, w: 5, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 7.5, w: 2, h: 1, static: true },
      ],
    },
  ],
  ['openeo']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 1, w: 5, h: 3.5, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 1250,
      cols: 3,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 1, w: 3, h: 3.5, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 1, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 2, w: 1, h: 2.5, static: true },
      ],
    },
  ],
  ['data-published']: [
    {
      minSize: 1400,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 5, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a3', x: 3, y: 0.5, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 1.5, w: 2, h: 3, static: true },
        { i: 'b2', x: 2, y: 1.5, w: 2, h: 3, static: true },
        { i: 'b6', x: 0, y: 4.5, w: 2, h: 3, static: true },
        { i: 'b4', x: 2, y: 4.5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 8, w: 5, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 8.5, w: 1, h: 1, static: true },
        { i: 'd1', x: 0, y: 9.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 920,
      maxSize: 1400,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 5, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a3', x: 3, y: 0.5, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 1.5, w: 2, h: 3, static: true },
        { i: 'b2', x: 2, y: 1.5, w: 2, h: 3, static: true },
        { i: 'b6', x: 0, y: 4.5, w: 2, h: 3, static: true },
        { i: 'b4', x: 2, y: 4.5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 8, w: 5, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 8.5, w: 1, h: 1, static: true },
        { i: 'd1', x: 0, y: 9.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 920,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 5, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 1.5, w: 1, h: 1, static: true },
        { i: 'a3', x: 1, y: 1.5, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 2.5, w: 2, h: 3, static: true },
        { i: 'b6', x: 0, y: 5.5, w: 2, h: 3, static: true },
        { i: 'b2', x: 0, y: 8.5, w: 2, h: 3, static: true },
        { i: 'b4', x: 0, y: 11.5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 15, w: 5, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 15.5, w: 1, h: 1, static: true },
        { i: 'd1', x: 0, y: 16.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 5, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 0, y: 1.5, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 2.5, w: 1, h: 1, static: true },
        { i: 'a3', x: 0, y: 3.5, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 4.5, w: 2, h: 3, static: true },
        { i: 'b6', x: 0, y: 7.5, w: 2, h: 3, static: true },
        { i: 'b2', x: 0, y: 10.5, w: 2, h: 3, static: true },
        { i: 'b4', x: 0, y: 13.5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 17, w: 5, h: 0.5, static: true },
        { i: 'd0', x: 0, y: 17.5, w: 1, h: 1, static: true },
        { i: 'd1', x: 0, y: 18.5, w: 2, h: 3, static: true },
      ],
    },
  ],
  ['performance']: [
    {
      minSize: 980,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 0.5, w: 1.33, h: 2.5, static: true },
        { i: 'b1', x: 1.33, y: 0.5, w: 1.33, h: 2.5, static: true },
        { i: 'b2', x: 2.66, y: 0.5, w: 1.33, h: 2.5, static: true },
        { i: 'b3', x: 0, y: 3, w: 1.33, h: 2.5, static: true },
        { i: 'b4', x: 1.33, y: 3, w: 1.33, h: 2.5, static: true },
        { i: 'b5', x: 2.66, y: 3, w: 1.33, h: 2.5, static: true },
        { i: 'b6', x: 0, y: 5.5, w: 1.33, h: 2.5, static: true },
        { i: 'divider1', x: 0, y: 8.5, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 9, w: 1.33, h: 1, static: true },
        { i: 'divider2', x: 0, y: 10.5, w: 4, h: 0.5, static: true },
        { i: 'a1', x: 0, y: 11, w: 3, h: 3, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 0.5, w: 1.5, h: 2.5, static: true },
        { i: 'b1', x: 1.5, y: 0.5, w: 1.5, h: 2.5, static: true },
        { i: 'b2', x: 0, y: 3, w: 1.5, h: 2.5, static: true },
        { i: 'b3', x: 1.5, y: 3, w: 1.5, h: 2.5, static: true },
        { i: 'b4', x: 0, y: 5.5, w: 1.5, h: 2.5, static: true },
        { i: 'b5', x: 1.5, y: 5.5, w: 1.5, h: 2.5, static: true },
        { i: 'b6', x: 0, y: 8, w: 1.5, h: 2.5, static: true },
        { i: 'divider1', x: 0, y: 11, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 11.5, w: 1.5, h: 1, static: true },
        { i: 'divider2', x: 0, y: 13, w: 4, h: 0.5, static: true },
        { i: 'a1', x: 0, y: 13.5, w: 3, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 790,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 0.5, w: 1, h: 2.5, static: true },
        { i: 'b1', x: 0, y: 3, w: 1, h: 2.5, static: true },
        { i: 'b2', x: 0, y: 5.5, w: 1, h: 2.5, static: true },
        { i: 'b3', x: 0, y: 8, w: 1, h: 2.5, static: true },
        { i: 'b4', x: 0, y: 10.5, w: 1, h: 2.5, static: true },
        { i: 'b5', x: 0, y: 13, w: 1, h: 2.5, static: true },
        { i: 'b6', x: 0, y: 15.5, w: 1, h: 2.5, static: true },
        { i: 'divider1', x: 0, y: 18.5, w: 1, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 19, w: 1, h: 1, static: true },
        { i: 'divider2', x: 0, y: 20.5, w: 1, h: 0.5, static: true },
        { i: 'a1', x: 0, y: 21, w: 1, h: 3, static: true },
      ],
    },
  ],
  ['mission-snapshot']: [
    {
      minSize: 1100,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 5, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 5, static: true },
        { i: 'a2', x: 2, y: 0, w: 1, h: 5, static: true },
        { i: 'a3', x: 3, y: 0, w: 1, h: 5, static: true },
        { i: 'b0', x: 0, y: 5, w: 2, h: 3, static: true },
        { i: 'b1', x: 2, y: 5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 650,
      maxSize: 1100,
      cols: 2,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 5, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 5, static: true },
        { i: 'a2', x: 0, y: 5, w: 1, h: 5, static: true },
        { i: 'a3', x: 1, y: 5, w: 1, h: 5, static: true },
        { i: 'b0', x: 0, y: 10, w: 2, h: 3, static: true },
        { i: 'b1', x: 0, y: 13, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 650,
      cols: 1,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 5, static: true },
        { i: 'a1', x: 0, y: 5, w: 1, h: 5, static: true },
        { i: 'a2', x: 0, y: 10, w: 1, h: 5, static: true },
        { i: 'a3', x: 0, y: 15, w: 1, h: 5, static: true },
        { i: 'b0', x: 0, y: 20, w: 2, h: 3, static: true },
        { i: 'b1', x: 0, y: 23, w: 2, h: 3, static: true },
      ],
    },
  ],
  ['sentinel-1']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a00', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a01', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 2, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 4, h: 3, static: true },
        { i: 'th1', x: 0, y: 5.5, w: 4, h: 3, static: true },
        { i: 'divider1', x: 0, y: 8.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 9, w: 2, h: 3, static: true },
        { i: 'b1', x: 2, y: 9, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 900,
      maxSize: 1250,
      cols: 3,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a00', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a01', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 2, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 4, h: 3, static: true },
        { i: 'th1', x: 0, y: 5.5, w: 4, h: 3, static: true },
        { i: 'divider1', x: 0, y: 8.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 9, w: 1.5, h: 3, static: true },
        { i: 'b1', x: 2, y: 9, w: 1.5, h: 3, static: true },
      ],
    },
    {
      minSize: 600,
      maxSize: 900,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a00', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a01', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 4.5, w: 4, h: 3, static: true },
        { i: 'th1', x: 0, y: 7.5, w: 4, h: 3, static: true },
        { i: 'divider1', x: 0, y: 10.5, w: 1, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 11, w: 2, h: 3, static: true },
        { i: 'b1', x: 0, y: 14, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 600,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a00', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a01', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 0, y: 4.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 6.5, w: 4, h: 3, static: true },
        { i: 'th1', x: 0, y: 9.5, w: 4, h: 3, static: true },
        { i: 'divider1', x: 0, y: 12.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 13, w: 1.5, h: 3, static: true },
        { i: 'b1', x: 0, y: 16, w: 1.5, h: 3, static: true },
      ],
    },
  ],
  ['sentinel-2']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 4, h: 3, static: true },
        { i: 'divider1', x: 0, y: 5.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 6, w: 2, h: 3, static: true },
        { i: 'b1', x: 2, y: 6, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 900,
      maxSize: 1250,
      cols: 3,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 3, h: 3, static: true },
        { i: 'divider1', x: 0, y: 5.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 6, w: 1.5, h: 3, static: true },
        { i: 'b1', x: 2, y: 6, w: 1.5, h: 3, static: true },
      ],
    },
    {
      minSize: 600,
      maxSize: 900,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 5.5, w: 1, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 6, w: 2, h: 3, static: true },
        { i: 'b1', x: 0, y: 9, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 600,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 4.5, w: 1, h: 3, static: true },
        { i: 'divider1', x: 0, y: 7.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 8, w: 1.5, h: 3, static: true },
        { i: 'b1', x: 0, y: 11, w: 1.5, h: 3, static: true },
      ],
    },
  ],
  ['sentinel-3']: [
    {
      minSize: 900,
      maxSize: 9999,
      cols: 3,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 2, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a3', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a4', x: 1, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a5', x: 2, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a6', x: 0, y: 4.5, w: 1, h: 2, static: true },
        { i: 'a7', x: 1, y: 4.5, w: 1, h: 2, static: true },
        { i: 'a8', x: 2, y: 4.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 6.5, w: 3, h: 3, static: true },
        { i: 'th1', x: 0, y: 9.5, w: 3, h: 3, static: true },
        { i: 'th2', x: 0, y: 12.5, w: 3, h: 3, static: true },
        { i: 'th3', x: 0, y: 15.5, w: 3, h: 3, static: true },
        { i: 'th4', x: 0, y: 18.5, w: 3, h: 3, static: true },
        { i: 'th5', x: 0, y: 21.5, w: 3, h: 3, static: true },
        { i: 'th6', x: 0, y: 24.5, w: 3, h: 3, static: true },
        { i: 'th7', x: 0, y: 27.5, w: 3, h: 3, static: true },
        { i: 'th8', x: 0, y: 30.5, w: 3, h: 3, static: true },
        { i: 'divider1', x: 0, y: 33.5, w: 3, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 34, w: 1.5, h: 3, static: true },
        { i: 'b1', x: 1.5, y: 34, w: 1.5, h: 3, static: true },
      ],
    },
    {
      minSize: 600,
      maxSize: 900,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 2, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a3', x: 1, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a4', x: 0, y: 4.5, w: 1, h: 2, static: true },
        { i: 'a5', x: 1, y: 4.5, w: 1, h: 2, static: true },
        { i: 'a6', x: 0, y: 6.5, w: 1, h: 2, static: true },
        { i: 'a7', x: 1, y: 6.5, w: 1, h: 2, static: true },
        { i: 'a8', x: 0, y: 8.5, w: 2, h: 2, static: true },
        { i: 'th0', x: 0, y: 10.5, w: 2, h: 3, static: true },
        { i: 'th1', x: 0, y: 13.5, w: 2, h: 3, static: true },
        { i: 'th2', x: 0, y: 16.5, w: 2, h: 3, static: true },
        { i: 'th3', x: 0, y: 19.5, w: 2, h: 3, static: true },
        { i: 'th4', x: 0, y: 22.5, w: 2, h: 3, static: true },
        { i: 'th5', x: 0, y: 25.5, w: 2, h: 3, static: true },
        { i: 'th6', x: 0, y: 28.5, w: 2, h: 3, static: true },
        { i: 'th7', x: 0, y: 31.5, w: 2, h: 3, static: true },
        { i: 'th8', x: 0, y: 34.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 37.5, w: 2, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 38, w: 2, h: 3, static: true },
        { i: 'b1', x: 0, y: 41, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 600,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 1, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 0, y: 4.5, w: 1, h: 2, static: true },
        { i: 'a3', x: 0, y: 6.5, w: 1, h: 2, static: true },
        { i: 'a4', x: 0, y: 8.5, w: 1, h: 2, static: true },
        { i: 'a5', x: 0, y: 10.5, w: 1, h: 2, static: true },
        { i: 'a6', x: 0, y: 12.5, w: 1, h: 2, static: true },
        { i: 'a7', x: 0, y: 14.5, w: 1, h: 2, static: true },
        { i: 'a8', x: 0, y: 16.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 18.5, w: 1, h: 3, static: true },
        { i: 'th1', x: 0, y: 21.5, w: 1, h: 3, static: true },
        { i: 'th2', x: 0, y: 24.5, w: 1, h: 3, static: true },
        { i: 'th3', x: 0, y: 27.5, w: 1, h: 3, static: true },
        { i: 'th4', x: 0, y: 30.5, w: 1, h: 3, static: true },
        { i: 'th5', x: 0, y: 33.5, w: 1, h: 3, static: true },
        { i: 'th6', x: 0, y: 36.5, w: 1, h: 3, static: true },
        { i: 'th7', x: 0, y: 39.5, w: 1, h: 3, static: true },
        { i: 'th8', x: 0, y: 42.5, w: 1, h: 3, static: true },
        { i: 'divider1', x: 0, y: 45.5, w: 1, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 46, w: 1, h: 3, static: true },
        { i: 'b1', x: 0, y: 49, w: 1, h: 3, static: true },
      ],
    },
  ],
  ['sentinel-5p']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 2, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 4, h: 3, static: true },
        { i: 'th1', x: 0, y: 5.5, w: 4, h: 3, static: true },
        { i: 'th2', x: 0, y: 8.5, w: 4, h: 3, static: true },
        { i: 'divider1', x: 0, y: 11.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 12, w: 4, h: 3, static: true },
        { i: 'b1', x: 0, y: 15, w: 4, h: 3, static: true },
      ],
    },
    {
      minSize: 900,
      maxSize: 1250,
      cols: 3,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 2, y: 0.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 2.5, w: 3, h: 3, static: true },
        { i: 'th1', x: 0, y: 5.5, w: 3, h: 3, static: true },
        { i: 'th2', x: 0, y: 8.5, w: 3, h: 3, static: true },
        { i: 'divider1', x: 0, y: 11.5, w: 3, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 12, w: 3, h: 3, static: true },
        { i: 'b1', x: 0, y: 15, w: 3, h: 3, static: true },
      ],
    },
    {
      minSize: 600,
      maxSize: 900,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 0, y: 2.5, w: 2, h: 2, static: true },
        { i: 'th0', x: 0, y: 4.5, w: 2, h: 3, static: true },
        { i: 'th1', x: 0, y: 7.5, w: 2, h: 3, static: true },
        { i: 'th2', x: 0, y: 10.5, w: 2, h: 3, static: true },
        { i: 'divider1', x: 0, y: 13.5, w: 4, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 14, w: 2, h: 3, static: true },
        { i: 'b1', x: 0, y: 17, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 600,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 2, static: true },
        { i: 'a1', x: 0, y: 2.5, w: 1, h: 2, static: true },
        { i: 'a2', x: 0, y: 4.5, w: 1, h: 2, static: true },
        { i: 'th0', x: 0, y: 6.5, w: 1, h: 3, static: true },
        { i: 'th1', x: 0, y: 9.5, w: 1, h: 3, static: true },
        { i: 'th2', x: 0, y: 12.5, w: 1, h: 3, static: true },
        { i: 'divider1', x: 0, y: 15.5, w: 1, h: 0.5, static: true },
        { i: 'b0', x: 0, y: 16, w: 1, h: 3, static: true },
        { i: 'b1', x: 0, y: 19, w: 1, h: 3, static: true },
      ],
    },
  ],
  ['stage-page']: [
    {
      minSize: 1000,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider1', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 2, h: 3, static: true },
        { i: 'a1', x: 2, y: 0.5, w: 2, h: 3, static: true },
        { i: 'a2', x: 0, y: 3.5, w: 1, h: 1, static: true },
        { i: 'a3', x: 1, y: 3.5, w: 1, h: 1, static: true },
        { i: 'a4', x: 2, y: 3.5, w: 1, h: 1, static: true },
        { i: 'a5', x: 0, y: 4.5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 7.5, w: 4, h: 0.5, static: true },
        { i: 'c0', x: 0, y: 8, w: 4, h: 3, static: true },
        { i: 'divider3', x: 0, y: 11, w: 4, h: 0.5, static: true },
        { i: 'x0', x: 0, y: 11.5, w: 4, h: 3, static: true },
        { i: 'divider4', x: 0, y: 14.5, w: 4, h: 0.5, static: true },
        { i: 'x1', x: 0, y: 15, w: 4, h: 3, static: true },
        { i: 'divider5', x: 0, y: 18, w: 4, h: 0.5, static: true },
        { i: 'x2', x: 0, y: 18.5, w: 4, h: 3, static: true },
        { i: 'divider6', x: 0, y: 21.5, w: 4, h: 0.5, static: true },
        { i: 'x3', x: 0, y: 22, w: 4, h: 3, static: true },
        { i: 'divider7', x: 0, y: 25, w: 4, h: 0.5, static: true },
        { i: 'map', x: 0, y: 25.5, w: 4, h: 6, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 1000,
      cols: 1,
      layout: [
        { i: 'divider1', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 2, h: 3, static: true },
        { i: 'a1', x: 2, y: 3.5, w: 2, h: 3, static: true },
        { i: 'a2', x: 0, y: 6.5, w: 1, h: 1, static: true },
        { i: 'a3', x: 1, y: 7.5, w: 1, h: 1, static: true },
        { i: 'a4', x: 2, y: 8.5, w: 1, h: 1, static: true },
        { i: 'a5', x: 0, y: 9.5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 12.5, w: 4, h: 0.5, static: true },
        { i: 'c0', x: 0, y: 13, w: 4, h: 3, static: true },
        { i: 'divider3', x: 0, y: 16, w: 4, h: 0.5, static: true },
        { i: 'x0', x: 0, y: 16.5, w: 4, h: 3, static: true },
        { i: 'divider4', x: 0, y: 19.5, w: 4, h: 0.5, static: true },
        { i: 'x1', x: 0, y: 20, w: 4, h: 3, static: true },
        { i: 'divider5', x: 0, y: 23, w: 4, h: 0.5, static: true },
        { i: 'x2', x: 0, y: 23.5, w: 4, h: 3, static: true },
        { i: 'divider6', x: 0, y: 26.5, w: 4, h: 0.5, static: true },
        { i: 'x3', x: 0, y: 27, w: 4, h: 3, static: true },
        { i: 'divider7', x: 0, y: 30, w: 4, h: 0.5, static: true },
        { i: 'map', x: 0, y: 30.5, w: 4, h: 6, static: true },
      ],
    },
  ],
  ['copernicus-contributing-missions']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'divider1', x: 0, y: 1.5, w: 4, h: 0.5, static: true },
        { i: 'b1', x: 0, y: 2, w: 2, h: 3, static: true },
        { i: 'b3', x: 2, y: 2, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 5, w: 4, h: 0.5, static: true },
        { i: 'c2', x: 0, y: 5.5, w: 2, h: 3, static: true },
        { i: 'c3', x: 2, y: 5.5, w: 2, h: 3, static: true },
        { i: 'c4', x: 0, y: 8.5, w: 2, h: 3, static: true },
        { i: 'c5', x: 2, y: 8.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 900,
      maxSize: 1250,
      cols: 3,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 3, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'divider1', x: 0, y: 1.5, w: 3, h: 0.5, static: true },
        { i: 'b1', x: 0, y: 2, w: 1.5, h: 3, static: true },
        { i: 'b3', x: 1.5, y: 2, w: 1.5, h: 3, static: true },
        { i: 'divider2', x: 0, y: 5, w: 3, h: 0.5, static: true },
        { i: 'c2', x: 0, y: 5.5, w: 1.5, h: 3, static: true },
        { i: 'c3', x: 1.5, y: 5.5, w: 1.5, h: 3, static: true },
        { i: 'c4', x: 0, y: 8.5, w: 1.5, h: 3, static: true },
        { i: 'c5', x: 1.5, y: 8.5, w: 1.5, h: 3, static: true },
      ],
    },
    {
      minSize: 600,
      maxSize: 900,
      cols: 2,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 2, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'divider1', x: 0, y: 1.5, w: 2, h: 0.5, static: true },
        { i: 'b1', x: 0, y: 2, w: 2, h: 3, static: true },
        { i: 'b3', x: 0, y: 5, w: 2, h: 3, static: true },
        { i: 'divider2', x: 0, y: 8, w: 2, h: 0.5, static: true },
        { i: 'c2', x: 0, y: 8.5, w: 2, h: 3, static: true },
        { i: 'c3', x: 0, y: 11.5, w: 2, h: 3, static: true },
        { i: 'c4', x: 0, y: 14.5, w: 2, h: 3, static: true },
        { i: 'c5', x: 0, y: 17.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 600,
      cols: 1,
      layout: [
        { i: 'divider0', x: 0, y: 0, w: 1, h: 0.5, static: true },
        { i: 'a0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'a1', x: 0, y: 1.5, w: 1, h: 1, static: true },
        { i: 'divider1', x: 0, y: 2.5, w: 1, h: 0.5, static: true },
        { i: 'b1', x: 0, y: 3, w: 1, h: 3, static: true },
        { i: 'b3', x: 0, y: 6, w: 1, h: 3, static: true },
        { i: 'divider2', x: 0, y: 9, w: 1, h: 0.5, static: true },
        { i: 'c2', x: 0, y: 9.5, w: 1, h: 3, static: true },
        { i: 'c3', x: 0, y: 12.5, w: 1, h: 3, static: true },
        { i: 'c4', x: 0, y: 15.5, w: 1, h: 3, static: true },
        { i: 'c5', x: 0, y: 18.5, w: 1, h: 3, static: true },
      ],
    },
  ],
};
