export const layouts = {
  // Service Insishgt
  ['/']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'a4', x: 4, y: 0, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 1, w: 1, h: 2, static: true },
        { i: 'b1', x: 1, y: 1, w: 2, h: 2, static: true },
        { i: 'b2', x: 3, y: 1, w: 1, h: 2, static: true },
        { i: 'b3', x: 4, y: 1, w: 1, h: 1, static: true },
        { i: 'c0', x: 0, y: 3, w: 2, h: 3, static: true },
        { i: 'c1', x: 2, y: 3, w: 2, h: 3, static: true },
        { i: 'd0', x: 4, y: 2, w: 1, h: 4, static: true },
      ],
    },
    {
      minSize: 980,
      maxSize: 1250,
      cols: 4,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'a4', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'b0', x: 2, y: 3, w: 1, h: 2, static: true },
        { i: 'b1', x: 0, y: 2, w: 2, h: 3, static: true },
        { i: 'b2', x: 2, y: 1, w: 1, h: 2, static: true },
        { i: 'b3', x: 1, y: 1, w: 1, h: 1, static: true },
        { i: 'c0', x: 3, y: 5, w: 2, h: 3, static: true },
        { i: 'c1', x: 0, y: 5, w: 2, h: 3, static: true },
        { i: 'd0', x: 3, y: 1, w: 1, h: 4, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'a3', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a4', x: 1, y: 1, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 2, w: 1, h: 2, static: true },
        { i: 'b1', x: 0, y: 4, w: 2, h: 2, static: true },
        { i: 'b2', x: 1, y: 2, w: 1, h: 2, static: true },
        { i: 'b3', x: 2, y: 1, w: 1, h: 1, static: true },
        { i: 'c0', x: 0, y: 6, w: 1.5, h: 3, static: true },
        { i: 'c1', x: 1.5, y: 6, w: 1.5, h: 3, static: true },
        { i: 'd0', x: 3, y: 1, w: 1, h: 4, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'a2', x: 0, y: 2, w: 1, h: 1, static: true },
        { i: 'a3', x: 0, y: 3, w: 1, h: 1, static: true },
        { i: 'a4', x: 0, y: 4, w: 1, h: 1, static: true },
        { i: 'b0', x: 0, y: 7, w: 2, h: 2, static: true },
        { i: 'b1', x: 0, y: 7, w: 2, h: 2, static: true },
        { i: 'b2', x: 0, y: 5, w: 2, h: 2, static: true },
        { i: 'b3', x: 2, y: 4, w: 1, h: 1, static: true },
        { i: 'c0', x: 0, y: 11, w: 2, h: 3, static: true },
        { i: 'c1', x: 1.5, y: 14, w: 2, h: 3, static: true },
        { i: 'd0', x: 1, y: 0, w: 1, h: 4, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 2,
      layout: [
        { i: 'a0', x: 0, y: 4, w: 2, h: 1, static: true },
        { i: 'a1', x: 0, y: 5, w: 2, h: 1, static: true },
        { i: 'a2', x: 0, y: 6, w: 2, h: 1, static: true },
        { i: 'a3', x: 0, y: 7, w: 2, h: 1, static: true },
        { i: 'a4', x: 0, y: 8, w: 2, h: 1, static: true },
        { i: 'b0', x: 0, y: 9, w: 2, h: 2, static: true },
        { i: 'b1', x: 0, y: 11, w: 2, h: 2, static: true },
        { i: 'b2', x: 0, y: 14, w: 2, h: 2, static: true },
        { i: 'b3', x: 2, y: 13, w: 2, h: 1, static: true },
        { i: 'c0', x: 0, y: 16, w: 2, h: 3, static: true },
        { i: 'c1', x: 1.5, y: 19, w: 2, h: 3, static: true },
        { i: 'd0', x: 0, y: 0, w: 2, h: 4, static: true },
      ],
    },
  ],
  ['/user-engagement']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'ue-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a4', x: 4, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-b0', x: 0, y: 1, w: 5, h: 5, static: true },
        { i: 'ue-c0', x: 0, y: 9, w: 2.5, h: 3, static: true },
        { i: 'ue-c1', x: 3, y: 9, w: 2.5, h: 3, static: true },
        { i: 'ue-d0', x: 0, y: 6, w: 3, h: 3, static: true },
        { i: 'ue-d1', x: 3, y: 6, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 980,
      maxSize: 1250,
      cols: 4,
      layout: [
        { i: 'ue-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a4', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'ue-b0', x: 1, y: 1, w: 3, h: 4, static: true },
        { i: 'ue-c0', x: 0, y: 5, w: 2, h: 2, static: true },
        { i: 'ue-c1', x: 0, y: 2, w: 1, h: 3, static: true },
        { i: 'ue-d0', x: 2, y: 5, w: 2, h: 2, static: true },
        { i: 'ue-d1', x: 0, y: 7, w: 4, h: 3, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'ue-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a3', x: 0, y: 1, w: 1.5, h: 1, static: true },
        { i: 'ue-a4', x: 1.5, y: 1, w: 1.5, h: 1, static: true },
        { i: 'ue-b0', x: 0, y: 2, w: 3, h: 4, static: true },
        { i: 'ue-c0', x: 0, y: 6, w: 1.5, h: 2.5, static: true },
        { i: 'ue-c1', x: 1.5, y: 6, w: 1.5, h: 2.5, static: true },
        { i: 'ue-d0', x: 0, y: 8.5, w: 1.5, h: 2.5, static: true },
        { i: 'ue-d1', x: 1.5, y: 8.5, w: 1.5, h: 2.5, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'ue-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a2', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'ue-a3', x: 1, y: 1, w: 1, h: 1, static: true },
        { i: 'ue-a4', x: 0, y: 2, w: 2, h: 1, static: true },
        { i: 'ue-b0', x: 0, y: 3, w: 2, h: 4, static: true },
        { i: 'ue-c0', x: 0, y: 12, w: 2, h: 2.5, static: true },
        { i: 'ue-c1', x: 0, y: 9.5, w: 2, h: 2.5, static: true },
        { i: 'ue-d0', x: 0, y: 7, w: 2, h: 2.5, static: true },
        { i: 'ue-d1', x: 0, y: 14.5, w: 2, h: 2.5, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'ue-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'ue-a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'ue-a2', x: 0, y: 2, w: 1, h: 1, static: true },
        { i: 'ue-a3', x: 0, y: 3, w: 1, h: 1, static: true },
        { i: 'ue-a4', x: 0, y: 4, w: 1, h: 1, static: true },
        { i: 'ue-b0', x: 0, y: 5, w: 1, h: 5, static: true },
        { i: 'ue-c0', x: 0, y: 15, w: 1, h: 2.5, static: true },
        { i: 'ue-c1', x: 0, y: 12.5, w: 1, h: 2.5, static: true },
        { i: 'ue-d0', x: 0, y: 10, w: 1, h: 2.5, static: true },
        { i: 'ue-d1', x: 0, y: 17.5, w: 1, h: 2.5, static: true },
      ],
    },
  ],
  ['/data-accessed']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'da-divider1', x: 0, y: 0, w: 5, h: 0.5, static: true },
        { i: 'da-b0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'da-b1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'da-b2', x: 0, y: 1.5, w: 2, h: 4, static: true },
        { i: 'da-b3', x: 2, y: 0.5, w: 3, h: 2, static: true },
        { i: 'da-b4', x: 2, y: 2.5, w: 3, h: 3, static: true },
        { i: 'da-divider2', x: 0, y: 6, w: 5, h: 0.5, static: true },
        { i: 'da-c0', x: 0, y: 6.5, w: 2.5, h: 3, static: true },
        { i: 'da-c1', x: 2.5, y: 6.5, w: 2.5, h: 3, static: true },
        { i: 'da-divider3', x: 0, y: 10, w: 5, h: 0.5, static: true },
        { i: 'da-d0', x: 0, y: 10.5, w: 2.5, h: 3, static: true },
        { i: 'da-d1', x: 2.5, y: 10.5, w: 2.5, h: 3, static: true },
        { i: 'da-d2', x: 0, y: 13.5, w: 2.5, h: 3, static: true },
        { i: 'da-d3', x: 2.5, y: 13.5, w: 2.5, h: 3, static: true },
        { i: 'da-divider0', x: 0, y: 14, w: 5, h: 0.5, static: true },
        { i: 'da-a0', x: 0, y: 14.5, w: 1, h: 1, static: true },
        { i: 'da-a1', x: 1, y: 14.5, w: 1, h: 1, static: true },
      ],
    },
    {
      minSize: 980,
      maxSize: 1250,
      cols: 4,
      layout: [
        { i: 'da-divider1', x: 0, y: 0, w: 4, h: 0.5, static: true },
        { i: 'da-b0', x: 0, y: 0.5, w: 1.5, h: 1, static: true },
        { i: 'da-b1', x: 0, y: 1.5, w: 1.5, h: 1, static: true },
        { i: 'da-b2', x: 0, y: 2.5, w: 2, h: 3, static: true },
        { i: 'da-b3', x: 1.5, y: 0.5, w: 2.5, h: 2, static: true },
        { i: 'da-b4', x: 2, y: 2.5, w: 2, h: 3, static: true },
        { i: 'da-divider2', x: 0, y: 6, w: 4, h: 0.5, static: true },
        { i: 'da-c0', x: 0, y: 6.5, w: 2, h: 3, static: true },
        { i: 'da-c1', x: 2.5, y: 6.5, w: 2, h: 3, static: true },
        { i: 'da-divider3', x: 0, y: 10, w: 4, h: 0.5, static: true },
        { i: 'da-d0', x: 0, y: 10.5, w: 2, h: 3, static: true },
        { i: 'da-d1', x: 2.5, y: 10.5, w: 2, h: 3, static: true },
        { i: 'da-d2', x: 0, y: 13.5, w: 2, h: 3, static: true },
        { i: 'da-d3', x: 2.5, y: 13.5, w: 2, h: 3, static: true },
        { i: 'da-divider0', x: 0, y: 14, w: 4, h: 0.5, static: true },
        { i: 'da-a0', x: 0, y: 14.5, w: 1, h: 1, static: true },
        { i: 'da-a1', x: 1, y: 14.5, w: 1, h: 1, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'da-divider1', x: 0, y: 0, w: 3, h: 0.5, static: true },
        { i: 'da-b0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'da-b1', x: 0, y: 1.5, w: 1, h: 1, static: true },
        { i: 'da-b2', x: 0, y: 2.5, w: 1.5, h: 3, static: true },
        { i: 'da-b3', x: 1.5, y: 0.5, w: 2, h: 2, static: true },
        { i: 'da-b4', x: 2, y: 2.5, w: 1.5, h: 3, static: true },
        { i: 'da-divider2', x: 0, y: 6, w: 3, h: 0.5, static: true },
        { i: 'da-c0', x: 0, y: 6.5, w: 1.5, h: 3, static: true },
        { i: 'da-c1', x: 2.5, y: 6.5, w: 1.5, h: 3, static: true },
        { i: 'da-divider3', x: 0, y: 10, w: 3, h: 0.5, static: true },
        { i: 'da-d0', x: 0, y: 10.5, w: 1.5, h: 3, static: true },
        { i: 'da-d1', x: 2.5, y: 10.5, w: 1.5, h: 3, static: true },
        { i: 'da-d2', x: 0, y: 13.5, w: 1.5, h: 3, static: true },
        { i: 'da-d3', x: 2.5, y: 13.5, w: 1.5, h: 3, static: true },
        { i: 'da-divider0', x: 0, y: 14, w: 3, h: 0.5, static: true },
        { i: 'da-a0', x: 0, y: 14.5, w: 1, h: 1, static: true },
        { i: 'da-a1', x: 1, y: 14.5, w: 1, h: 1, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'da-divider1', x: 0, y: 0, w: 2, h: 0.5, static: true },
        { i: 'da-b0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'da-b1', x: 1, y: 0.5, w: 1, h: 1, static: true },
        { i: 'da-b2', x: 0, y: 3.5, w: 2, h: 3, static: true },
        { i: 'da-b3', x: 0, y: 1.5, w: 2, h: 2, static: true },
        { i: 'da-b4', x: 0, y: 6.5, w: 2, h: 3, static: true },
        { i: 'da-divider2', x: 0, y: 10, w: 2, h: 0.5, static: true },
        { i: 'da-c0', x: 0, y: 10.5, w: 2, h: 3, static: true },
        { i: 'da-c1', x: 0, y: 13.5, w: 2, h: 3, static: true },
        { i: 'da-divider3', x: 0, y: 17, w: 2, h: 0.5, static: true },
        { i: 'da-d0', x: 0, y: 17.5, w: 2, h: 3, static: true },
        { i: 'da-d1', x: 0, y: 20.5, w: 2, h: 3, static: true },
        { i: 'da-d2', x: 0, y: 23.5, w: 2, h: 3, static: true },
        { i: 'da-d3', x: 0, y: 26.5, w: 2, h: 3, static: true },
        { i: 'da-divider0', x: 0, y: 27, w: 2, h: 0.5, static: true },
        { i: 'da-a0', x: 0, y: 27.5, w: 2, h: 1, static: true },
        { i: 'da-a1', x: 0, y: 28.5, w: 2, h: 1, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'da-divider1', x: 0, y: 0, w: 1, h: 0.5, static: true },
        { i: 'da-b0', x: 0, y: 0.5, w: 1, h: 1, static: true },
        { i: 'da-b1', x: 0, y: 1.5, w: 1, h: 1, static: true },
        { i: 'da-b2', x: 0, y: 2.5, w: 1, h: 3, static: true },
        { i: 'da-b3', x: 0, y: 5.5, w: 1, h: 2, static: true },
        { i: 'da-b4', x: 0, y: 7.5, w: 1, h: 3, static: true },
        { i: 'da-divider2', x: 0, y: 11, w: 1, h: 0.5, static: true },
        { i: 'da-c0', x: 0, y: 11.5, w: 1, h: 3, static: true },
        { i: 'da-c1', x: 0, y: 14.5, w: 1, h: 3, static: true },
        { i: 'da-divider3', x: 0, y: 18, w: 1, h: 0.5, static: true },
        { i: 'da-d0', x: 0, y: 18.5, w: 1, h: 3, static: true },
        { i: 'da-d1', x: 0, y: 21.5, w: 1, h: 3, static: true },
        { i: 'da-d2', x: 0, y: 24.5, w: 1, h: 3, static: true },
        { i: 'da-d3', x: 0, y: 27.5, w: 1, h: 3, static: true },
        { i: 'da-divider0', x: 0, y: 28, w: 1, h: 0.5, static: true },
        { i: 'da-a0', x: 0, y: 28.5, w: 1, h: 1, static: true },
        { i: 'da-a1', x: 0, y: 29.5, w: 1, h: 1, static: true },
      ],
    },
  ],
  ['/sentinel-hub']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'sh-a0', x: 0, y: 0, w: 2.5, h: 3, static: true },
        { i: 'sh-a1', x: 2.5, y: 0, w: 2.5, h: 3, static: true },
        { i: 'sh-divider0', x: 0, y: 3.5, w: 5, h: 0.5, static: true },
        { i: 'sh-b0', x: 0, y: 4, w: 1.25, h: 2.5, static: true },
        { i: 'sh-b1', x: 1.25, y: 4, w: 1.25, h: 2.5, static: true },
        { i: 'sh-b2', x: 2.5, y: 4, w: 1.25, h: 2.5, static: true },
        { i: 'sh-b3', x: 3.75, y: 4, w: 1.25, h: 2.5, static: true },
        { i: 'sh-b4', x: 0, y: 6.5, w: 1.25, h: 2.5, static: true },
        { i: 'sh-b5', x: 1.25, y: 6.5, w: 1.25, h: 2.5, static: true },
        { i: 'sh-b6', x: 2.5, y: 6.5, w: 1.25, h: 2.5, static: true },
      ],
    },
    {
      minSize: 980,
      maxSize: 1250,
      cols: 4,
      layout: [
        { i: 'sh-a0', x: 0, y: 0, w: 2, h: 3, static: true },
        { i: 'sh-a1', x: 2.5, y: 0, w: 2, h: 3, static: true },
        { i: 'sh-divider0', x: 0, y: 3.5, w: 4, h: 0.5, static: true },
        { i: 'sh-b0', x: 0, y: 4, w: 1.33, h: 2.5, static: true },
        { i: 'sh-b1', x: 1.33, y: 4, w: 1.33, h: 2.5, static: true },
        { i: 'sh-b2', x: 2.66, y: 4, w: 1.33, h: 2.5, static: true },
        { i: 'sh-b3', x: 0, y: 6.5, w: 1.33, h: 2.5, static: true },
        { i: 'sh-b4', x: 1.33, y: 6.5, w: 1.33, h: 2.5, static: true },
        { i: 'sh-b5', x: 2.66, y: 6.5, w: 1.33, h: 2.5, static: true },
        { i: 'sh-b6', x: 0, y: 9, w: 1.33, h: 2.5, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 980,
      cols: 3,
      layout: [
        { i: 'sh-a0', x: 0, y: 0, w: 1.5, h: 3, static: true },
        { i: 'sh-a1', x: 2.5, y: 0, w: 1.5, h: 3, static: true },
        { i: 'sh-divider0', x: 0, y: 3.5, w: 3, h: 0.5, static: true },
        { i: 'sh-b0', x: 0, y: 4, w: 1, h: 2.5, static: true },
        { i: 'sh-b1', x: 1, y: 4, w: 1, h: 2.5, static: true },
        { i: 'sh-b2', x: 2, y: 4, w: 1, h: 2.5, static: true },
        { i: 'sh-b3', x: 0, y: 6.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b4', x: 1, y: 6.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b5', x: 2, y: 6.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b6', x: 0, y: 9, w: 1, h: 2.5, static: true },
      ],
    },
    {
      minSize: 630,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'sh-a0', x: 0, y: 0, w: 2, h: 3, static: true },
        { i: 'sh-a1', x: 0, y: 3, w: 2, h: 3, static: true },
        { i: 'sh-divider0', x: 0, y: 6.5, w: 2, h: 0.5, static: true },
        { i: 'sh-b0', x: 0, y: 7, w: 1, h: 2.5, static: true },
        { i: 'sh-b1', x: 1, y: 7, w: 1, h: 2.5, static: true },
        { i: 'sh-b2', x: 0, y: 9.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b3', x: 1, y: 9.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b4', x: 0, y: 12, w: 1, h: 2.5, static: true },
        { i: 'sh-b5', x: 1, y: 12, w: 1, h: 2.5, static: true },
        { i: 'sh-b6', x: 0, y: 14.5, w: 1, h: 2.5, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 630,
      cols: 1,
      layout: [
        { i: 'sh-a0', x: 0, y: 0, w: 1, h: 3, static: true },
        { i: 'sh-a1', x: 0, y: 3, w: 1, h: 3, static: true },
        { i: 'sh-divider0', x: 0, y: 6.5, w: 1, h: 0.5, static: true },
        { i: 'sh-b0', x: 0, y: 7, w: 1, h: 2.5, static: true },
        { i: 'sh-b1', x: 0, y: 9.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b2', x: 0, y: 12, w: 1, h: 2.5, static: true },
        { i: 'sh-b3', x: 0, y: 14.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b4', x: 0, y: 17, w: 1, h: 2.5, static: true },
        { i: 'sh-b5', x: 0, y: 19.5, w: 1, h: 2.5, static: true },
        { i: 'sh-b6', x: 0, y: 22, w: 1, h: 2.5, static: true },
      ],
    },
  ],
  ['/openeo']: [
    {
      minSize: 1250,
      maxSize: 9999,
      cols: 5,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 1, w: 5, h: 3.5, static: true },
      ],
    },
    {
      minSize: 790,
      maxSize: 1250,
      cols: 3,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 1, w: 3, h: 3.5, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 790,
      cols: 2,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 1, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'oe-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'oe-a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'oe-b0', x: 0, y: 2, w: 1, h: 2.5, static: true },
      ],
    },
  ],
  ['/data-published']: [
    {
      minSize: 1400,
      maxSize: 9999,
      cols: 4,
      layout: [
        { i: 'dp0-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'dp-divider0', x: 0, y: 1, w: 5, h: 0.5, static: true },
        { i: 'dp-a0', x: 0, y: 1.5, w: 2, h: 3, static: true },
        { i: 'dp-a1', x: 2, y: 1.5, w: 2, h: 3, static: true },
        { i: 'dp-a2', x: 0, y: 4.5, w: 2, h: 3, static: true },
        { i: 'dp-a3', x: 2, y: 4.5, w: 2, h: 3, static: true },
        { i: 'dp-divider1', x: 0, y: 8, w: 5, h: 0.5, static: true },
        { i: 'dp-b0', x: 0, y: 8.5, w: 2, h: 3, static: true },
        { i: 'dp-b1', x: 2, y: 8.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 920,
      maxSize: 1400,
      cols: 4,
      layout: [
        { i: 'dp0-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a2', x: 2, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a3', x: 3, y: 0, w: 1, h: 1, static: true },
        { i: 'dp-divider0', x: 0, y: 1, w: 5, h: 0.5, static: true },
        { i: 'dp-a0', x: 0, y: 1.5, w: 4, h: 3, static: true },
        { i: 'dp-a1', x: 0, y: 4.5, w: 4, h: 3, static: true },
        { i: 'dp-a2', x: 0, y: 7.5, w: 4, h: 3, static: true },
        { i: 'dp-a3', x: 0, y: 10.5, w: 4, h: 3, static: true },
        { i: 'dp-divider1', x: 0, y: 14, w: 4, h: 0.5, static: true },
        { i: 'dp-b0', x: 0, y: 14.5, w: 2, h: 3, static: true },
        { i: 'dp-b1', x: 2, y: 14.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 540,
      maxSize: 920,
      cols: 2,
      layout: [
        { i: 'dp0-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a1', x: 1, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a2', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'dp0-a3', x: 1, y: 1, w: 1, h: 1, static: true },
        { i: 'dp-divider0', x: 0, y: 2, w: 5, h: 0.5, static: true },
        { i: 'dp-a0', x: 0, y: 2.5, w: 4, h: 3, static: true },
        { i: 'dp-a1', x: 0, y: 5.5, w: 4, h: 3, static: true },
        { i: 'dp-a2', x: 0, y: 8.5, w: 4, h: 3, static: true },
        { i: 'dp-a3', x: 0, y: 11.5, w: 4, h: 3, static: true },
        { i: 'dp-divider1', x: 0, y: 15, w: 4, h: 0.5, static: true },
        { i: 'dp-b0', x: 0, y: 15.5, w: 2, h: 3, static: true },
        { i: 'dp-b1', x: 0, y: 18.5, w: 2, h: 3, static: true },
      ],
    },
    {
      minSize: 0,
      maxSize: 540,
      cols: 1,
      layout: [
        { i: 'dp0-a0', x: 0, y: 0, w: 1, h: 1, static: true },
        { i: 'dp0-a1', x: 0, y: 1, w: 1, h: 1, static: true },
        { i: 'dp0-a2', x: 0, y: 2, w: 1, h: 1, static: true },
        { i: 'dp0-a3', x: 0, y: 3, w: 1, h: 1, static: true },
        { i: 'dp-divider0', x: 0, y: 4, w: 5, h: 0.5, static: true },
        { i: 'dp-a0', x: 0, y: 4.5, w: 4, h: 3, static: true },
        { i: 'dp-a1', x: 0, y: 7.5, w: 4, h: 3, static: true },
        { i: 'dp-a2', x: 0, y: 10.5, w: 4, h: 3, static: true },
        { i: 'dp-a3', x: 0, y: 13.5, w: 4, h: 3, static: true },
        { i: 'dp-divider1', x: 0, y: 17, w: 4, h: 0.5, static: true },
        { i: 'dp-b0', x: 0, y: 17.5, w: 2, h: 3, static: true },
        { i: 'dp-b1', x: 0, y: 20.5, w: 2, h: 3, static: true },
      ],
    },
  ],
};
